package iai.atp;

import iai.lib.Edge;
import iai.lib.Graph;

class World {
	/* Road, an edge that can be either clear or flooded */
	static class Road extends Edge {
		final boolean clear;
		Road(int v, double weight, boolean clear) {
			super(v, weight);
			this.clear = clear;
		}
	}

	final Graph<Road> roads;

	/**
	 * Vehicle
	 */
	static class Vehicle {
		/** vehicle name */
		final String name;
		/** vehicle garage location */
		final int garage;
		/** vehicle speeds on C)lear and F)looded roards */
		final double cspeed, fspeed;

		/**
		 * Constructs a Vehicle, the name is autogenerated
		 * @param garage the node in which the vehicle is parked
		 * @param cspeed speed on clear road
		 * @param fspeed speed on flooded road
		 */
		Vehicle(int garage, double cspeed, double fspeed) {
			this.garage = garage;
			this.cspeed = cspeed;
			this.fspeed = fspeed;
			this.name = genName();
		}

		/** increases every time a new vehicle is allocated
		 * to provide unique names of the engines */
		private static int namegen = 0;
		/** automatic name generator */
		private String genName() {return Integer.toString(namegen++);}
	}

	final Vehicle[] vehicles;

	World(Graph<Road> roads, Vehicle[] vehicles) {
		this.roads = roads;
		this.vehicles = vehicles;
	}
}